### ISSUE TITLE
No releases.

### ISSUE THREAD

**Issue by benalb** [kieselsteini/cgo#14]
I would like to package cgo for [Void Linux ](https://voidlinux.org),but  they do not accept any packages containing non-release versions.

**Comment by kieselsteini** [comment]
Hi,
I can create a release and will go with semantic versioning. I'll do some cleanup and create a proper release :)

**Comment by apetresc** [comment]
@kieselsteini Hi :) Any update on a tagged release? Now that the repo has >50 stars it is eligible for Homebrew packaging, but they require a tagged release to build from. If you can add one, I can submit my Formula asap!

**Comment by kieselsteini** [comment]
I released now the version 0.5.0 of cgo which resolved an issue :)

**Comment by benalb** [comment]
I'm closing this issue. https://github.com/void-linux/void-packages/pull/11703  
Thank you :)
