### ISSUE TITLE
URIs not working properly

### ISSUE THREAD

**Issue by haydenhv** [kieselsteini/cgo#19]
cgo seems not to understand the `<gophertype>` as described in RFC 4266.

For example, if I run `cgo gopher://bitreich.org/1/lawn/` I get: `error: Not a directory`

`cgo gopher://bitreich.org/lawn/` encounters the same issue, and the only way I can get it work is by using `cgo gopher://bitreich.org//lawn/`, which means I need to modify URIs when I get them in a *stupid* way.

**Comment by n0a110w** [comment]
I, too, have encountered this.

**Comment by haydenhv** [comment]
I believe I've found a fix - the uri variable needs a simple increment

```
diff --git a/cgo.c b/cgo.c
index 1ed65fc..ad356c5 100644
--- a/cgo.c
+++ b/cgo.c
@@ -759,6 +759,7 @@ int parse_uri(const char *uri)
         parsed_port[i] = 0;
     } else snprintf(parsed_port, sizeof(parsed_port), "%d", 70);
     /* parse selector */
+    uri++;
     if (*uri == '/') {
         for (i = 0, ++uri; *uri; ++uri)
             if (i < sizeof(parsed_selector) - 1)
```

**Comment by n0a110w** [comment]
Patch works great, thanks @haydenhv

**Comment by kieselsteini** [comment]
Yes ```cgo``` has a very strange way to create gopher URIs. I'll try to fix the parser :)

In the meanwhile you can try out ```delve```, as it is a more powerful replacement for ```cgo``` and it handles URIs correct.

https://github.com/kieselsteini/delve

**Comment by kieselsteini** [comment]
I added your idea and fixed the gopher URI parsing. Also use correct URIs now in history.

**Comment by haydenhv** [comment]
Thanks! Works well.
