### ISSUE TITLE
Issue with Initial Selector

### ISSUE THREAD

**Issue by crcx** [kieselsteini/cgo#8]
It appears that cgo is sending a `/` as the default selector. RFC1436 indicates that a client should send a CR/LF sequence to get the initial directory.

Reference https://tools.ietf.org/rfc/rfc1436.txt section 2:

    Server:          {Accepts connection but says nothing}
    Client: <CR><LF> {Sends an empty line: Meaning "list what you have"}
    Server:          {Sends a series of lines, each ending with CR LF}

**Comment by kieselsteini** [comment]
This is a fair point. I should fix it, although it is not an issue as most gopher servers in the wild will recognize "/" as the root directory anyways.

**Comment by kieselsteini** [comment]
This issue should be resolved in master and also the tagged 0.5.0 release.
